export const applicationPermissions = [
	{
		key: "page.overview",
		kind: "page",
		group: "客户工作台",
		label: "项目总览",
		navigationKey: "overview",
		iconKey: "building",
	},
	{
		key: "page.monitor",
		kind: "page",
		group: "客户工作台",
		label: "AI 监测",
		navigationKey: "monitor",
		iconKey: "activity",
	},
	{
		key: "page.evidence",
		kind: "page",
		group: "客户工作台",
		label: "证据中心",
		navigationKey: "evidence",
		iconKey: "database",
	},
	{
		key: "page.audit",
		kind: "page",
		group: "客户工作台",
		label: "官网审计",
		navigationKey: "audit",
		iconKey: "shield",
	},
	{
		key: "page.diagnosis",
		kind: "page",
		group: "客户工作台",
		label: "差距诊断",
		navigationKey: "diagnosis",
		iconKey: "search",
	},
	{
		key: "page.remediation",
		kind: "page",
		group: "客户工作台",
		label: "整改中心",
		navigationKey: "remediation",
		iconKey: "checklist",
	},
	{
		key: "page.attribution",
		kind: "page",
		group: "客户工作台",
		label: "业务归因",
		navigationKey: "attribution",
		iconKey: "route",
	},
	{
		key: "page.report",
		kind: "page",
		group: "客户工作台",
		label: "复测报告",
		navigationKey: "report",
		iconKey: "report",
	},
	{
		key: "page.knowledge",
		kind: "page",
		group: "机构管理",
		label: "问题知识库",
		navigationKey: "knowledge",
		iconKey: "book",
	},
	{
		key: "page.settings",
		kind: "page",
		group: "机构管理",
		label: "平台设置",
		navigationKey: "settings",
		iconKey: "settings",
	},
	{
		key: "page.members",
		kind: "page",
		group: "机构管理",
		label: "机构成员",
		navigationKey: "members",
		iconKey: "users",
	},
	{
		key: "page.audit_logs",
		kind: "page",
		group: "机构管理",
		label: "审计日志",
		navigationKey: "auditLogs",
		iconKey: "history",
	},
	{
		key: "page.service_logs",
		kind: "page",
		group: "机构管理",
		label: "运行日志",
		navigationKey: "serviceLogs",
		iconKey: "activity",
	},
	{
		key: "page.rbac",
		kind: "page",
		group: "系统管理",
		label: "权限配置",
		navigationKey: "rbac",
		iconKey: "lock",
		systemOnly: true,
		desktopOnly: true,
	},
	{
		key: "page.organizations",
		kind: "page",
		group: "系统管理",
		label: "多租户管理",
		navigationKey: "organizations",
		iconKey: "organizations",
		systemOnly: true,
		desktopOnly: true,
	},
	{ key: "project.create", kind: "action", group: "客户与建档", label: "新建客户" },
	{ key: "project.onboard", kind: "action", group: "客户与建档", label: "分析并确认客户建档" },
	{ key: "monitor.run", kind: "action", group: "监测", label: "运行快审、基线与复测" },
	{ key: "monitor.schedule", kind: "action", group: "监测", label: "配置自动监测" },
	{ key: "audit.run", kind: "action", group: "分析", label: "运行官网审计" },
	{ key: "diagnosis.run", kind: "action", group: "分析", label: "生成规则诊断" },
	{ key: "agent.run", kind: "action", group: "Agent", label: "运行 Agent 草稿" },
	{ key: "agent.approve", kind: "action", group: "Agent", label: "批准或拒绝 Agent 草稿" },
	{ key: "remediation.manage", kind: "action", group: "整改", label: "管理整改任务与验收" },
	{ key: "attribution.import", kind: "action", group: "归因", label: "导入业务归因数据" },
	{ key: "report.generate", kind: "action", group: "报告", label: "生成报告与文档" },
	{ key: "report.share", kind: "action", group: "报告", label: "创建和撤销报告分享" },
	{ key: "knowledge.manage", kind: "action", group: "机构管理", label: "维护问题知识库" },
	{ key: "settings.manage", kind: "action", group: "机构管理", label: "维护模型与平台设置" },
	{ key: "members.manage", kind: "action", group: "机构管理", label: "新增和停用成员" },
	{ key: "logs.export", kind: "action", group: "日志", label: "导出运行日志" },
	{ key: "logs.retention", kind: "action", group: "日志", label: "执行日志保留清理" },
	{
		key: "rbac.manage",
		kind: "action",
		group: "系统管理",
		label: "管理角色与用户授权",
		systemOnly: true,
		desktopOnly: true,
	},
	{
		key: "organization.manage",
		kind: "action",
		group: "系统管理",
		label: "管理机构与机构授权",
		systemOnly: true,
		desktopOnly: true,
	},
] as const;

export type ApplicationPermission = (typeof applicationPermissions)[number]["key"];

export const applicationPermissionKeys = applicationPermissions.map(
	(permission) => permission.key,
) as ApplicationPermission[];

export const legacyRolePermissionPresets = {
	admin: applicationPermissionKeys.filter(
		(permission) => !applicationPermissions.find((item) => item.key === permission && "systemOnly" in item),
	),
	analyst: applicationPermissionKeys.filter(
		(permission) =>
			![
				"page.settings",
				"page.members",
				"page.audit_logs",
				"page.service_logs",
				"page.rbac",
				"settings.manage",
				"members.manage",
				"logs.export",
				"logs.retention",
				"rbac.manage",
			].includes(permission),
	),
	viewer: applicationPermissionKeys.filter(
		(permission) =>
			permission.startsWith("page.") &&
			!applicationPermissions.find((item) => item.key === permission && "systemOnly" in item),
	),
} satisfies Record<"admin" | "analyst" | "viewer", ApplicationPermission[]>;
