#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

readonly DEFAULT_INSTALL_DIR="/opt/geo-console"
readonly DEFAULT_BACKUP_DIR="/var/backups/geo-console"

install_dir="$DEFAULT_INSTALL_DIR"
backup_dir=""
domain=""
admin_email=""
capture_concurrency="1"
create_swap="true"
install_docker="true"
stage_dir=""

log() {
	printf '[GEO installer] %s\n' "$*"
}

warn() {
	printf '[GEO installer] WARNING: %s\n' "$*" >&2
}

fail() {
	printf '[GEO installer] ERROR: %s\n' "$*" >&2
	exit 1
}

usage() {
	cat <<'EOF'
GEO Console private release installer

Usage:
  geo-console-<version>.run --domain demo.example.com --admin-email admin@example.com

Options:
  --domain DOMAIN              Public HTTPS domain (required on first install)
  --admin-email EMAIL          Bootstrap administrator email (required on first install)
  --backup-dir PATH            Host backup directory (default: /var/backups/geo-console)
  --capture-concurrency N      Capture concurrency (default: 1)
  --install-dir PATH           Installation root (default: /opt/geo-console)
  --no-swap                    Do not create a 2 GiB swap file when no swap exists
  --skip-docker-install        Require Docker Engine and Compose to be preinstalled
  -h, --help                   Show this help

The installer preserves the shared .env, secrets, backups, PostgreSQL volume,
evidence volume, and Caddy state when a newer release bundle is installed.
EOF
}

while (($# > 0)); do
	case "$1" in
		--domain)
			domain="${2:-}"
			shift 2
			;;
		--admin-email)
			admin_email="${2:-}"
			shift 2
			;;
		--backup-dir)
			backup_dir="${2:-}"
			shift 2
			;;
		--capture-concurrency)
			capture_concurrency="${2:-}"
			shift 2
			;;
		--install-dir)
			install_dir="${2:-}"
			shift 2
			;;
		--no-swap)
			create_swap="false"
			shift
			;;
		--skip-docker-install)
			install_docker="false"
			shift
			;;
		-h|--help)
			usage
			exit 0
			;;
		*)
			fail "unknown argument: $1"
			;;
	esac
done

cleanup() {
	if [[ -n "$stage_dir" && -d "$stage_dir" ]]; then rm -rf -- "$stage_dir"; fi
}
trap cleanup EXIT

env_value() {
	local file="$1"
	local key="$2"
	awk -F= -v key="$key" '$1 == key { sub(/^[^=]*=/, ""); print; exit }' "$file"
}

prompt_if_missing() {
	local variable_name="$1"
	local prompt="$2"
	local value="${!variable_name}"
	[[ -n "$value" ]] && return
	[[ -r /dev/tty ]] || fail "$prompt must be provided as an argument"
	read -r -p "$prompt: " value </dev/tty
	printf -v "$variable_name" '%s' "$value"
}

validate_inputs() {
	[[ "$domain" =~ ^([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?\.)+[A-Za-z]{2,63}$ ]] || fail "invalid domain: $domain"
	[[ "$admin_email" =~ ^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$ ]] || fail "invalid administrator email"
	[[ "$capture_concurrency" =~ ^[1-9][0-9]*$ ]] || fail "capture concurrency must be a positive integer"
	((capture_concurrency <= 8)) || fail "capture concurrency above 8 is not supported by this installer"
	[[ "$install_dir" == /* && "$install_dir" != "/" && "$install_dir" != *[[:space:]]* ]] || fail "install directory must be a safe absolute path"
	[[ "$backup_dir" == /* && "$backup_dir" != "/" && "$backup_dir" != *[[:space:]]* ]] || fail "backup directory must be a safe absolute path"
}

require_linux_root() {
	[[ "$(uname -s)" == "Linux" ]] || fail "this installer supports Linux servers only"
	((EUID == 0)) || fail "run the installer as root, for example with sudo"
	command -v tar >/dev/null 2>&1 || fail "tar is required to extract the release bundle"
}

extract_release() {
	local archive_line
	archive_line="$(awk '/^__ARCHIVE_BELOW__$/ { print NR + 1; exit }' "$0")"
	[[ -n "$archive_line" ]] || fail "release payload marker is missing; run a bundle generated by deploy/package.sh"
	stage_dir="$(mktemp -d)"
	tail -n +"$archive_line" "$0" | tar -xzf - -C "$stage_dir"
	[[ -f "$stage_dir/payload/.geo-release" ]] || fail "release manifest is missing"
	[[ -f "$stage_dir/payload/compose.yaml" ]] || fail "release compose.yaml is missing"
	[[ -x "$stage_dir/payload/deploy/geo-console" ]] || fail "release management command is missing"
}

install_base_dependencies() {
	local missing="false"
	for command in curl openssl; do
		command -v "$command" >/dev/null 2>&1 || missing="true"
	done
	[[ "$missing" == "false" ]] && return
	command -v apt-get >/dev/null 2>&1 || fail "automatic dependency installation requires Ubuntu or Debian"
	log "Installing base dependencies"
	apt-get update
	DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl openssl
}

configure_docker_repository() {
	# shellcheck disable=SC1091
	source /etc/os-release
	case "${ID:-}" in
		ubuntu|debian) ;;
		*) fail "automatic Docker installation supports Ubuntu and Debian only" ;;
	esac
	local suite="${VERSION_CODENAME:-}"
	if [[ "$ID" == "ubuntu" && -n "${UBUNTU_CODENAME:-}" ]]; then suite="$UBUNTU_CODENAME"; fi
	[[ -n "$suite" ]] || fail "could not determine the Linux release codename"
	install -m 0755 -d /etc/apt/keyrings
	curl -fsSL "https://download.docker.com/linux/$ID/gpg" -o /etc/apt/keyrings/docker.asc
	chmod a+r /etc/apt/keyrings/docker.asc
	cat >/etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/$ID
Suites: $suite
Components: stable
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/docker.asc
EOF
}

ensure_docker() {
	if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
		if command -v systemctl >/dev/null 2>&1; then systemctl enable --now docker; fi
		docker info >/dev/null 2>&1 || fail "Docker daemon is not available"
		return
	fi
	[[ "$install_docker" == "true" ]] || fail "Docker Engine and Compose plugin are required"
	command -v apt-get >/dev/null 2>&1 || fail "automatic Docker installation requires Ubuntu or Debian"
	log "Installing Docker Engine from the official repository"
	configure_docker_repository
	apt-get update
	DEBIAN_FRONTEND=noninteractive apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
	systemctl enable --now docker
	docker info >/dev/null 2>&1 || fail "Docker daemon did not start"
}

ensure_swap() {
	[[ "$create_swap" == "true" ]] || return
	if swapon --show --noheadings 2>/dev/null | grep -q .; then return; fi
	if [[ -e /swapfile ]]; then
		warn "/swapfile exists but is not active; leaving it unchanged"
		return
	fi
	log "No swap detected; creating /swapfile (2 GiB) for the 2-core/4-GB demo profile"
	if command -v fallocate >/dev/null 2>&1; then
		fallocate -l 2G /swapfile
	else
		dd if=/dev/zero of=/swapfile bs=1M count=2048 status=progress
	fi
	chmod 600 /swapfile
	mkswap /swapfile >/dev/null
	if swapon /swapfile; then
		grep -qF '/swapfile none swap sw 0 0' /etc/fstab || printf '/swapfile none swap sw 0 0\n' >>/etc/fstab
	else
		warn "swap could not be enabled; continuing without it"
	fi
}

preflight_resources() {
	local cpu_count memory_kib available_kib
	cpu_count="$(nproc)"
	memory_kib="$(awk '/MemTotal/ { print $2 }' /proc/meminfo)"
	available_kib="$(df -Pk "$install_dir" | awk 'NR == 2 { print $4 }')"
	((cpu_count >= 2)) || warn "fewer than 2 CPU cores detected"
	((memory_kib >= 3500000)) || warn "less than 4 GB RAM detected"
	if ((available_kib < 30 * 1024 * 1024)); then warn "less than 30 GB free disk detected"; fi
	if ! getent ahosts "$domain" >/dev/null 2>&1; then
		warn "$domain does not resolve yet; Caddy cannot issue HTTPS until DNS points to this server"
	fi
}

configure_environment() {
	local env_file="$install_dir/shared/.env"
	if [[ -f "$env_file" ]]; then
		local existing_domain existing_email
		existing_domain="$(env_value "$env_file" GEO_DOMAIN)"
		existing_email="$(env_value "$env_file" GEO_ADMIN_EMAIL)"
		[[ "$existing_domain" == "$domain" ]] || fail "existing deployment uses domain $existing_domain"
		[[ "$existing_email" == "$admin_email" ]] || fail "existing deployment uses administrator $existing_email"
		if ! grep -q '^GEO_DESKTOP_RELEASES_DIR=' "$env_file"; then
			printf '\nGEO_DESKTOP_RELEASES_DIR=%s/shared/desktop\n' "$install_dir" >>"$env_file"
		fi
		log "Reusing existing environment configuration"
		return
	fi
	cat >"$env_file" <<EOF
GEO_DOMAIN=$domain
GEO_ADMIN_EMAIL=$admin_email
GEO_CAPTURE_CONCURRENCY=$capture_concurrency
GEO_BACKUP_DIR=$backup_dir
GEO_LOG_RETENTION_DAYS=90
GEO_DESKTOP_RELEASES_DIR=$install_dir/shared/desktop

GEO_OBJECT_STORE=local
GEO_S3_ENDPOINT=
GEO_S3_REGION=auto
GEO_S3_BUCKET=
GEO_S3_ACCESS_KEY_ID=
GEO_S3_SECRET_ACCESS_KEY=
GEO_S3_FORCE_PATH_STYLE=false
EOF
	chmod 600 "$env_file"
}

generate_secret() {
	local path="$1"
	local bytes="$2"
	[[ -f "$path" ]] && return
	openssl rand -base64 "$bytes" >"$path"
	chmod 600 "$path"
}

configure_secrets() {
	local secret_dir="$install_dir/shared/secrets"
	install -m 0700 -d "$secret_dir"
	generate_secret "$secret_dir/postgres_password" 32
	generate_secret "$secret_dir/master_key" 32
	generate_secret "$secret_dir/admin_password" 24
	generate_secret "$secret_dir/log_service_token" 32
	chmod 600 "$secret_dir"/*
	local master_key_bytes
	master_key_bytes="$(openssl base64 -d -A <"$secret_dir/master_key" | wc -c | tr -d ' ')"
	[[ "$master_key_bytes" == "32" ]] || fail "master key is not a Base64-encoded 32-byte value"
}

install_release_files() {
	local release_id release_dir
	release_id="$(env_value "$stage_dir/payload/.geo-release" RELEASE_ID)"
	[[ "$release_id" =~ ^[A-Za-z0-9._-]+$ ]] || fail "invalid release identifier"
	release_dir="$install_dir/releases/$release_id"
	if [[ -d "$release_dir" ]]; then
		printf '[GEO installer] Release already exists: %s\n' "$release_id" >&2
	else
		mv "$stage_dir/payload" "$release_dir"
	fi
	ln -sfn "$install_dir/shared/.env" "$release_dir/.env"
	ln -sfn "$install_dir/shared/secrets" "$release_dir/secrets"
	chmod +x "$release_dir/deploy/geo-console"
	printf '%s' "$release_dir"
}

activate_release_link() {
	local release_dir="$1"
	[[ ! -e "$install_dir/current" || -L "$install_dir/current" ]] || fail "$install_dir/current exists and is not a symbolic link"
	rm -f -- "$install_dir/current.next"
	ln -s "$release_dir" "$install_dir/current.next"
	mv -Tf "$install_dir/current.next" "$install_dir/current"
	ln -sfn "$install_dir/current/deploy/geo-console" /usr/local/bin/geo-console
}

main() {
	require_linux_root
	extract_release
	local existing_env="$install_dir/shared/.env"
	if [[ -f "$existing_env" ]]; then
		[[ -n "$domain" ]] || domain="$(env_value "$existing_env" GEO_DOMAIN)"
		[[ -n "$admin_email" ]] || admin_email="$(env_value "$existing_env" GEO_ADMIN_EMAIL)"
		[[ -n "$backup_dir" ]] || backup_dir="$(env_value "$existing_env" GEO_BACKUP_DIR)"
	fi
	[[ -n "$backup_dir" ]] || backup_dir="$DEFAULT_BACKUP_DIR"
	prompt_if_missing domain "Public domain"
	prompt_if_missing admin_email "Administrator email"
	validate_inputs
	install_base_dependencies
	ensure_docker
	ensure_swap
	install -m 0700 -d "$install_dir" "$install_dir/releases" "$install_dir/shared" "$backup_dir"
	install -m 0755 -d "$install_dir/shared/desktop"
	chmod 700 "$install_dir" "$install_dir/releases" "$install_dir/shared" "$backup_dir"
	preflight_resources
	configure_environment
	configure_secrets
	local release_dir old_release=""
	release_dir="$(install_release_files)"
	if [[ -L "$install_dir/current" ]]; then old_release="$(readlink -f "$install_dir/current")"; fi
	log "Preparing release $(basename "$release_dir") while the current release stays online"
	GEO_INSTALL_DIR="$release_dir" GEO_INSTALL_ROOT="$install_dir" "$release_dir/deploy/geo-console" prepare
	if [[ -n "$old_release" && "$old_release" != "$release_dir" ]]; then
		log "Creating a paired backup before switching releases"
		GEO_INSTALL_DIR="$old_release" GEO_INSTALL_ROOT="$install_dir" "$old_release/deploy/geo-console" backup
		GEO_INSTALL_DIR="$old_release" GEO_INSTALL_ROOT="$install_dir" "$old_release/deploy/geo-console" stop
	fi
	activate_release_link "$release_dir"
	GEO_INSTALL_DIR="$release_dir" GEO_INSTALL_ROOT="$install_dir" "$release_dir/deploy/geo-console" activate
	if [[ -z "$old_release" ]]; then
		GEO_INSTALL_DIR="$release_dir" GEO_INSTALL_ROOT="$install_dir" "$release_dir/deploy/geo-console" backup
	fi
	GEO_INSTALL_DIR="$release_dir" GEO_INSTALL_ROOT="$install_dir" "$release_dir/deploy/geo-console" doctor
	log "Release installed: https://$domain"
	log "Read the bootstrap password with: sudo geo-console show-admin-password"
	log "Back up $install_dir/shared/secrets/master_key offline before configuring provider keys"
}

main "$@"
exit 0

__ARCHIVE_BELOW__
