import {
	IconActivity,
	IconArticle,
	IconBook2,
	IconBuilding,
	IconBuildingCommunity,
	IconClipboardCheck,
	IconDatabase,
	IconHistory,
	IconLoader2,
	IconLockAccess,
	IconReportAnalytics,
	IconRoute,
	IconSearch,
	IconSettings,
	IconShieldCheck,
	IconSparkles,
	IconUsers,
} from "@tabler/icons-react";
import type { View } from "../types";

export const views: Array<{ id: View; label: string; icon: typeof IconActivity }> = [
	{ id: "workbench", label: "AI 工作台", icon: IconSparkles },
	{ id: "overview", label: "项目总览", icon: IconBuilding },
	{ id: "monitor", label: "AI 监测", icon: IconActivity },
	{ id: "evidence", label: "证据中心", icon: IconDatabase },
	{ id: "audit", label: "官网审计", icon: IconShieldCheck },
	{ id: "diagnosis", label: "差距诊断", icon: IconSearch },
	{ id: "remediation", label: "整改中心", icon: IconClipboardCheck },
	{ id: "attribution", label: "业务归因", icon: IconRoute },
	{ id: "report", label: "复测报告", icon: IconReportAnalytics },
	{ id: "articles", label: "优化文章", icon: IconArticle },
	{ id: "customers", label: "客户管理", icon: IconBuilding },
	{ id: "knowledge", label: "问题知识库", icon: IconBook2 },
	{ id: "settings", label: "平台设置", icon: IconSettings },
	{ id: "members", label: "机构成员", icon: IconUsers },
	{ id: "auditLogs", label: "审计日志", icon: IconHistory },
	{ id: "serviceLogs", label: "运行日志", icon: IconActivity },
	{ id: "rbac", label: "权限配置", icon: IconLockAccess },
	{ id: "organizations", label: "多租户管理", icon: IconBuildingCommunity },
];
export const navigationIcons: Record<string, typeof IconActivity> = {
	activity: IconActivity,
	article: IconArticle,
	sparkles: IconSparkles,
	book: IconBook2,
	building: IconBuilding,
	checklist: IconClipboardCheck,
	database: IconDatabase,
	history: IconHistory,
	lock: IconLockAccess,
	organizations: IconBuildingCommunity,
	report: IconReportAnalytics,
	route: IconRoute,
	search: IconSearch,
	settings: IconSettings,
	shield: IconShieldCheck,
	users: IconUsers,
};
export const projectPagePermissions = [
	"page.workbench",
	"page.overview",
	"page.monitor",
	"page.evidence",
	"page.audit",
	"page.diagnosis",
	"page.remediation",
	"page.attribution",
	"page.report",
	"page.articles",
];
